[package]
name = "hara-crypto-hash-sha256"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.78"

[lib]
crate-type = ["cdylib"]

[dependencies]
hara-abi = { path = "../../../../technology/hara/core/rust/abi" }
hara-hta = { path = "../../../../technology/hara/core/rust/hta-codec" }
